#!/usr/bin/env bash
# Sync the app source to the build Mac. ALWAYS use this instead of hand-rolling
# rsync flags — the exclude list below is hard-won:
#
#   ios/, android/   generated by `expo prebuild` on the Mac and NOT in git.
#                    --delete removed the whole Xcode project once, costing a
#                    full regenerate + pod install.
#   *.log            build/ship logs live on the Mac; --delete wiped a running
#                    ship.log and blinded us mid-release (four times).
#   build/           archives + .ipa outputs, expensive to recreate.
#   node_modules/    installed per-machine.
#
# ~/asc-tools/ (TestFlight helpers) deliberately lives OUTSIDE the sync target
# for the same reason — an earlier --delete killed the running watcher.
#
# Usage: ./scripts/sync-mac.sh [user@host]
set -euo pipefail
HERE="$(cd "$(dirname "$0")" && pwd)"
APP_DIR="$(cd "$HERE/.." && pwd)"
TARGET="${1:-rponnarasu@100.76.141.120}"
SSHOPT="-o StrictHostKeyChecking=accept-new -o ConnectTimeout=25"

exec rsync -az --delete \
  --exclude 'node_modules' --exclude 'e2e/node_modules' \
  --exclude 'ios' --exclude 'android' \
  --exclude '.expo' --exclude '.git' \
  --exclude 'build' --exclude '*.log' \
  -e "ssh $SSHOPT" \
  "$APP_DIR/" "$TARGET:agents-mobile/"
