import { Platform, StyleSheet } from "react-native"
import { useTheme } from "../lib/useTheme"
import type { Theme } from "../lib/theme"

/**
 * The app's stylesheet, as a factory over the active theme. Backgrounds, text,
 * borders, inputs, code, chips etc. resolve from the palette (src/lib/theme.ts)
 * so every screen follows light/dark automatically — this is what stops white
 * pages leaking in dark mode. The palette is intentionally muted/pastel (sage
 * accent, clay danger, warm sand cards) rather than neon so it reads as crafted,
 * not generic. A few intent tints (sand "waiting on you" cards, muted steer/queue
 * chips, translucent scrims) are kept literal because they read on both themes.
 *
 * Consume via the `useStyles()` hook (below), not a module-level `styles`, so a
 * theme change repaints. makeStyles is memoised per Theme (LIGHT/DARK are stable
 * singletons) so StyleSheet.create runs at most twice.
 */
const mono = Platform.OS === "ios" ? "Menlo" : "monospace"

function buildStyles(t: Theme) {
  const s = StyleSheet.create({
    screen: { flex: 1, padding: 16, backgroundColor: t.bg },
    center: { flex: 1, justifyContent: "center", alignItems: "center", backgroundColor: t.bg },
    label: { fontSize: 13, fontWeight: "600", color: t.text, marginTop: 12, marginBottom: 6 },
    hint: { fontSize: 12, color: t.textMuted, marginTop: 8 },
    error: { color: t.danger, marginTop: 12 },
    input: {
      borderWidth: 1,
      borderColor: t.border,
      borderRadius: 8,
      paddingHorizontal: 12,
      paddingVertical: 10,
      fontSize: 15,
      color: t.text,
      backgroundColor: t.inputBg,
    },
    button: {
      backgroundColor: t.accent,
      borderRadius: 8,
      paddingVertical: 14,
      alignItems: "center",
      marginTop: 20,
    },
    buttonText: { color: "#fff", fontSize: 16, fontWeight: "600" },
    headerAction: { color: t.danger, fontSize: 15 },
    row: {
      flexDirection: "row",
      alignItems: "center",
      paddingHorizontal: 16,
      paddingVertical: 14,
      borderBottomWidth: StyleSheet.hairlineWidth,
      borderBottomColor: t.border,
    },
    rowTitle: { fontSize: 16, fontWeight: "600", color: t.text },
    rowSub: { fontSize: 12, color: t.textMuted, marginTop: 2 },
    pill: {
      backgroundColor: t.chipBg,
      borderRadius: 14,
      paddingHorizontal: 12,
      paddingVertical: 6,
      marginLeft: 8,
    },
    pillText: { fontSize: 13, color: t.text, fontWeight: "500" },
    // Tab screens (Hosts / Projects / Profile)
    hostRow: {
      flexDirection: "row",
      alignItems: "center",
      paddingHorizontal: 16,
      paddingVertical: 14,
      borderBottomWidth: StyleSheet.hairlineWidth,
    },
    hostName: { fontSize: 16, fontWeight: "500" },
    tabAddRow: {
      flexDirection: "row",
      alignItems: "center",
      gap: 8,
      paddingHorizontal: 16,
      paddingVertical: 16,
    },
    tabAddText: { fontSize: 15, fontWeight: "600" },
    projectRow: {
      flexDirection: "row",
      alignItems: "center",
      gap: 12,
      paddingHorizontal: 16,
      paddingVertical: 15,
      borderBottomWidth: StyleSheet.hairlineWidth,
    },
    projectName: { flex: 1, fontSize: 16 },
    profileInfoRow: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      paddingHorizontal: 18,
      paddingVertical: 12,
      gap: 12,
    },
    profileInfoLabel: { fontSize: 14, color: t.textMuted },
    profileInfoValue: { flex: 1, textAlign: "right", fontSize: 14 },
    mono: { fontFamily: "Courier", fontSize: 12, color: t.textMuted, marginTop: 8 },
    // WhatsApp-style chat list
    chatRow: {
      flexDirection: "row",
      alignItems: "center",
      paddingHorizontal: 16,
      paddingVertical: 12,
      borderBottomWidth: StyleSheet.hairlineWidth,
      borderBottomColor: t.border,
      gap: 12,
    },
    avatar: {
      width: 46,
      height: 46,
      borderRadius: 23,
      backgroundColor: t.accent,
      alignItems: "center",
      justifyContent: "center",
    },
    avatarText: { color: "#fff", fontSize: 18, fontWeight: "600" },
    chatName: { fontSize: 16, fontWeight: "600", color: t.text },
    chatSub: { fontSize: 13, color: t.textMuted, marginTop: 2 },
    chatTime: { fontSize: 12, color: t.textMuted },
    chatNameUnread: { fontWeight: "800" },
    chatTimeUnread: { color: t.accent, fontWeight: "700" },
    chatMetaCol: { alignItems: "flex-end", gap: 5 },
    unreadDot: { width: 10, height: 10, borderRadius: 5, backgroundColor: t.accent },
    // WhatsApp-style filter chips + archived reveal row (Chats list header).
    filterRow: { flexDirection: "row", gap: 8, paddingHorizontal: 12, paddingBottom: 8 },
    filterChip: {
      paddingHorizontal: 14,
      paddingVertical: 6,
      borderRadius: 16,
      backgroundColor: t.chipBg,
    },
    filterChipActive: { backgroundColor: t.accent },
    filterChipText: { fontSize: 13, fontWeight: "600", color: t.textMuted },
    filterChipTextActive: { color: "#fff" },
    archivedRow: {
      flexDirection: "row",
      alignItems: "center",
      gap: 10,
      paddingHorizontal: 16,
      paddingVertical: 12,
      borderBottomWidth: 1,
      borderBottomColor: t.border,
    },
    archivedRowText: { fontSize: 15, fontWeight: "600", color: t.text },
    // Collapsible project group header (Projects chip view).
    projectHeader: {
      flexDirection: "row",
      alignItems: "center",
      gap: 8,
      paddingHorizontal: 16,
      paddingVertical: 9,
      backgroundColor: t.chipBg,
      borderBottomWidth: 1,
      borderBottomColor: t.border,
    },
    projectHeaderText: { flex: 1, fontSize: 13, fontWeight: "700", color: t.textMuted, textTransform: "uppercase", letterSpacing: 0.5 },
    projectHeaderCount: { fontSize: 13, fontWeight: "600", color: t.textMuted },
    // AskUserQuestion quick-reply card — amber family (kept literal: means
    // "the agent is waiting on you" and reads on both themes).
    auqCard: {
      marginTop: 8,
      padding: 10,
      borderRadius: 10,
      backgroundColor: "#efe9dd",
      borderWidth: 1,
      borderColor: "#d6c39a",
    },
    auqHeader: { flexDirection: "row", alignItems: "center", gap: 5, marginBottom: 2 },
    auqHeaderText: { fontSize: 12, fontWeight: "700", color: "#7a6a45" },
    auqQuestion: { fontSize: 14.5, fontWeight: "600", color: "#3e3626", marginBottom: 6 },
    auqOptions: { flexDirection: "row", flexWrap: "wrap", gap: 7 },
    auqChip: {
      flexDirection: "row",
      alignItems: "center",
      gap: 5,
      paddingHorizontal: 12,
      paddingVertical: 8,
      borderRadius: 16,
      backgroundColor: "#fff",
      borderWidth: 1,
      borderColor: "#d0c09a",
    },
    auqChipPicked: { backgroundColor: t.accent, borderColor: t.accent },
    auqChipText: { fontSize: 13.5, fontWeight: "600", color: "#3e3626" },
    auqChipTextPicked: { color: "#fff" },
    auqDesc: { fontSize: 12, color: "#8a7a58", marginTop: 6 },
    auqSubmit: {
      marginTop: 10,
      paddingVertical: 9,
      borderRadius: 8,
      backgroundColor: t.accent,
      alignItems: "center",
    },
    auqSubmitText: { color: "#fff", fontSize: 14, fontWeight: "700" },
    // In-thread search bar
    threadSearchBar: {
      flexDirection: "row",
      alignItems: "center",
      gap: 8,
      paddingHorizontal: 10,
      paddingVertical: 6,
      backgroundColor: t.surface,
    },
    threadSearchInput: {
      flex: 1,
      height: 34,
      borderRadius: 17,
      paddingHorizontal: 12,
      fontSize: 14,
      color: t.text,
      backgroundColor: t.inputBg,
    },
    threadSearchCount: { fontSize: 12, minWidth: 44, textAlign: "center", color: t.textMuted },
    headerBtn: { fontSize: 22, paddingHorizontal: 4, color: t.accent },
    // Hamburger drawer (the mobile "left-hand column")
    scrim: { ...StyleSheet.absoluteFillObject, backgroundColor: "rgba(0,0,0,0.35)" },
    drawer: {
      position: "absolute",
      top: 0,
      left: 0,
      bottom: 0,
      backgroundColor: t.surface,
      paddingTop: 56,
      shadowColor: "#000",
      shadowOffset: { width: 2, height: 0 },
      shadowOpacity: 0.2,
      shadowRadius: 8,
      elevation: 16,
    },
    drawerBrand: { fontSize: 22, fontWeight: "700", color: t.text, paddingHorizontal: 16, paddingBottom: 4 },
    drawerSection: {
      fontSize: 11,
      fontWeight: "700",
      color: t.textMuted,
      letterSpacing: 1,
      paddingHorizontal: 16,
      marginTop: 18,
      marginBottom: 4,
    },
    drawerSectionHeader: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      paddingRight: 16,
      marginTop: 18,
      marginBottom: 4,
    },
    drawerItem: { paddingHorizontal: 16, paddingVertical: 11 },
    drawerRow: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      paddingLeft: 16,
      paddingRight: 12,
      paddingVertical: 9,
    },
    drawerCheckRow: { flexDirection: "row", alignItems: "center", gap: 6 },
    drawerItemText: { fontSize: 15, fontWeight: "600", color: t.text },
    drawerItemMuted: { fontSize: 15, color: t.textMuted },
    // Theme switch (System / Light / Dark) segmented control
    segRow: { flexDirection: "row", gap: 6, paddingHorizontal: 16, marginTop: 6 },
    seg: {
      flex: 1,
      alignItems: "center",
      paddingVertical: 7,
      borderRadius: 9,
      backgroundColor: t.chipBg,
      borderWidth: 1,
      borderColor: t.border,
    },
    segActive: { backgroundColor: t.accent, borderColor: t.accent },
    segText: { fontSize: 12.5, fontWeight: "600", color: t.textMuted },
    segTextActive: { color: "#fff", fontWeight: "700" },
    // Chat thread (bubbles)
    threadList: { flex: 1, backgroundColor: t.thread },
    // The thread list is `inverted`, which flips the content container — so
    // paddingTop applies at the visual BOTTOM and paddingBottom at the visual
    // TOP. Values are set for the visual result: 24px of breathing room under
    // the newest message (above the composer), 8px at the top.
    threadContent: { paddingTop: 24, paddingBottom: 8 },
    bubbleUser: {
      alignSelf: "flex-end",
      backgroundColor: t.bubbleUser,
      borderRadius: 12,
      padding: 10,
      marginVertical: 3,
      marginHorizontal: 10,
      maxWidth: "82%",
    },
    bubbleAssistant: {
      alignSelf: "flex-start",
      backgroundColor: t.bubbleAgent,
      borderRadius: 12,
      padding: 10,
      marginVertical: 3,
      marginHorizontal: 10,
      maxWidth: "82%",
    },
    bubbleText: { fontSize: 15, color: t.text, lineHeight: 20 },
    systemPill: {
      alignSelf: "center",
      backgroundColor: t.chipBg,
      borderRadius: 10,
      paddingHorizontal: 10,
      paddingVertical: 4,
      marginVertical: 6,
      maxWidth: "88%",
    },
    systemText: { fontSize: 12, color: t.textMuted, textAlign: "center" },
    toolChip: {
      flexDirection: "row",
      alignItems: "center",
      alignSelf: "flex-start",
      maxWidth: "100%",
      gap: 6,
      backgroundColor: t.chipBg,
      borderRadius: 8,
      paddingHorizontal: 8,
      paddingVertical: 5,
      marginTop: 4,
    },
    toolChipErr: { backgroundColor: t.dangerBg },
    // flexShrink lets a long, unbreakable tool name (e.g. an MCP tool id) ellipsize
    // instead of pushing the chip — and the time/chevron — past the bubble edge.
    toolChipText: { fontSize: 12, color: t.text, flexShrink: 1 },
    toolChipTime: { fontSize: 10, color: t.textMuted, marginLeft: 2 },
    // Per-message wall-clock time (WhatsApp-style), bottom-right of a bubble.
    msgTime: { fontSize: 10, color: t.textMuted, alignSelf: "flex-end", marginTop: 3 },
    // Row holding an optional pin glyph + the timestamp, bottom-right of a bubble.
    bubbleMetaRow: { flexDirection: "row", alignItems: "center", justifyContent: "flex-end", gap: 4 },
    // Pinned-message banner under the chat header.
    pinnedBanner: { flexDirection: "row", alignItems: "center", gap: 8, paddingHorizontal: 14, paddingVertical: 8, borderBottomWidth: StyleSheet.hairlineWidth },
    pinnedBannerLabel: { fontSize: 11, fontWeight: "600" },
    pinnedBannerText: { fontSize: 13 },
    bubbleImage: { width: 220, height: 160, borderRadius: 8, marginTop: 6 },
    typingText: { fontSize: 12, color: t.textMuted, marginLeft: 16, marginVertical: 6 },
    // Composer
    composerWrap: {
      backgroundColor: t.surface,
      borderTopWidth: StyleSheet.hairlineWidth,
      borderTopColor: t.border,
    },
    composerBar: {
      flexDirection: "row",
      alignItems: "flex-end",
      paddingHorizontal: 8,
      paddingTop: 8,
      paddingBottom: 8,
      gap: 8,
    },
    composerInput: {
      flex: 1,
      maxHeight: 120,
      minHeight: 40,
      borderWidth: 1,
      borderColor: t.border,
      borderRadius: 20,
      paddingHorizontal: 14,
      paddingTop: Platform.OS === "ios" ? 10 : 8,
      paddingBottom: Platform.OS === "ios" ? 10 : 8,
      fontSize: 16,
      lineHeight: 20,
      color: t.text,
      backgroundColor: t.inputBg,
    },
    circleBtn: {
      width: 40,
      height: 40,
      borderRadius: 20,
      alignItems: "center",
      justifyContent: "center",
    },
    sendBtn: { backgroundColor: t.accent },
    sendBtnDisabled: { backgroundColor: t.border },
    sendBtnText: { color: "#fff", fontSize: 19, fontWeight: "700", lineHeight: 22 },
    stopBtn: { backgroundColor: t.danger },
    stopBtnText: { color: "#fff", fontSize: 14, fontWeight: "700" },
    gearBtn: { backgroundColor: t.chipBg },
    gearBtnText: { fontSize: 17, lineHeight: 20 },
    runBar: {
      flexDirection: "row",
      alignItems: "center",
      gap: 8,
      marginHorizontal: 10,
      marginBottom: 6,
      paddingLeft: 12,
      paddingRight: 6,
      paddingVertical: 6,
      borderRadius: 18,
      backgroundColor: t.chipBg,
    },
    runText: { flex: 1, fontSize: 13, color: t.textMuted, fontWeight: "500" },
    runQueued: { fontSize: 12, color: t.textMuted },
    // Floating "jump to latest" button, bottom-right above the composer.
    jumpBtn: {
      position: "absolute",
      right: 14,
      // Anchored to the LIST's bottom edge (its flex:1 wrapper), which always
      // sits just above the composer + run bar — so a small gap is all that's
      // needed, and it never collides with the variable-height controls below.
      bottom: 12,
      width: 32,
      height: 32,
      borderRadius: 16,
      backgroundColor: t.accent,
      alignItems: "center",
      justifyContent: "center",
      shadowColor: "#000",
      shadowOpacity: 0.25,
      shadowRadius: 4,
      shadowOffset: { width: 0, height: 2 },
      elevation: 4,
    },
    // WhatsApp-style floating day header: centered, pinned near the top of the
    // thread, fades in only while scrolling.
    scrollDatePill: {
      position: "absolute",
      top: 8,
      alignSelf: "center",
      backgroundColor: t.chipBg,
      paddingHorizontal: 12,
      paddingVertical: 5,
      borderRadius: 12,
      shadowColor: "#000",
      shadowOpacity: 0.15,
      shadowRadius: 3,
      shadowOffset: { width: 0, height: 1 },
      elevation: 3,
      zIndex: 10,
    },
    scrollDateText: {
      fontSize: 12,
      fontWeight: "600",
      color: t.textMuted,
    },
    stopGhost: {
      paddingHorizontal: 12,
      paddingVertical: 6,
      borderRadius: 14,
      backgroundColor: t.surface,
      borderWidth: 1,
      borderColor: "#e0b4ae",
    },
    stopGhostText: { color: t.danger, fontSize: 13, fontWeight: "700" },
    sendModeChip: {
      alignSelf: "flex-start",
      flexDirection: "row",
      alignItems: "center",
      gap: 7,
      marginLeft: 56,
      marginBottom: 6,
      paddingHorizontal: 12,
      paddingVertical: 7,
      borderRadius: 16,
      backgroundColor: t.chipBg,
      borderWidth: 1,
    },
    // Semantic border only — sage = queue (gentle, after), clay = interrupt now.
    sendModeQueue: { borderColor: t.accent },
    sendModeSteer: { borderColor: t.danger },
    // Label stays high-contrast so it's readable on both themes; the icon +
    // border carry the colour meaning.
    sendModeText: { fontSize: 13, fontWeight: "700", color: t.text },
    sendModeTextQueue: { color: t.text },
    sendModeTextSteer: { color: t.text },
    sendModeSwap: { fontSize: 11, color: t.textMuted, fontWeight: "600" },
    // Queue / Interrupt actions embedded in the working pill (between "Working…"
    // and Stop). Neutral, compact chips — the label says what each does; no
    // accent/danger colours (keeps the pill calm, not a traffic light).
    runModeToggle: {
      flexDirection: "row",
      alignItems: "center",
      gap: 5,
      paddingHorizontal: 10,
      paddingVertical: 5,
      borderRadius: 13,
      borderWidth: 1,
      borderColor: t.border,
      backgroundColor: t.surface,
    },
    runModeText: { fontSize: 12, fontWeight: "600", color: t.textMuted },
    steerBtn: { backgroundColor: "#c99a63" },
    statusLine: {
      flexDirection: "row",
      alignItems: "center",
      gap: 6,
      paddingHorizontal: 14,
      paddingTop: 6,
    },
    statusText: { fontSize: 12, color: t.textMuted },
    // Composer settings bottom sheet (permission mode + model)
    sheetScrim: { flex: 1, backgroundColor: "rgba(0,0,0,0.45)", justifyContent: "flex-end" },
    sheet: {
      backgroundColor: t.surface,
      borderTopLeftRadius: 20,
      borderTopRightRadius: 20,
      borderTopWidth: StyleSheet.hairlineWidth,
      borderColor: t.border,
      paddingTop: 8,
      paddingBottom: 34,
    },
    sheetGrabber: {
      alignSelf: "center",
      width: 40,
      height: 4,
      borderRadius: 2,
      backgroundColor: t.border,
      marginBottom: 4,
    },
    sheetTitle: {
      fontSize: 17,
      fontWeight: "700",
      color: t.text,
      paddingHorizontal: 18,
      paddingTop: 6,
      paddingBottom: 2,
    },
    sheetSection: {
      fontSize: 11,
      fontWeight: "700",
      color: t.textMuted,
      letterSpacing: 1,
      paddingHorizontal: 18,
      marginTop: 16,
    },
    sheetHint: { fontSize: 12, color: t.textMuted, paddingHorizontal: 18, marginTop: 4, lineHeight: 17 },
    // Session settings: collapsible grouped cards. Each group is a rounded card
    // with a tappable header (icon + title + summary + chevron); the body reveals
    // on tap. Stable positions + icons build muscle memory; collapsing the long
    // tail (prompt/goal/loops/stats) kills the "one giant scroll" crowding.
    spCard: {
      marginHorizontal: 14,
      marginTop: 12,
      borderRadius: 14,
      borderWidth: 1,
      borderColor: t.border,
      backgroundColor: t.surface,
      overflow: "hidden",
    },
    spCardHead: {
      flexDirection: "row",
      alignItems: "center",
      gap: 12,
      paddingHorizontal: 14,
      paddingVertical: 14,
    },
    spCardIcon: {
      width: 30, height: 30, borderRadius: 8,
      alignItems: "center", justifyContent: "center",
      backgroundColor: t.chipBg,
    },
    spCardTitle: { fontSize: 15, fontWeight: "700", color: t.text },
    spCardSummary: { fontSize: 12, color: t.textMuted, marginTop: 1 },
    spCardBody: {
      paddingBottom: 12,
      borderTopWidth: StyleSheet.hairlineWidth,
      borderTopColor: t.border,
    },
    // Capabilities screen (skills + MCP CRUD).
    capAddRow: { flexDirection: "row", alignItems: "center", gap: 6, paddingHorizontal: 18, paddingVertical: 12 },
    capAddText: { fontSize: 14, fontWeight: "600" },
    capRow: { flexDirection: "row", alignItems: "center", gap: 10, paddingHorizontal: 18, paddingVertical: 12, borderTopWidth: StyleSheet.hairlineWidth, borderTopColor: t.border },
    capRowName: { fontSize: 15, fontWeight: "500" },
    capRowDesc: { fontSize: 12, marginTop: 2 },
    capBadge: { fontSize: 10, borderWidth: StyleSheet.hairlineWidth, borderRadius: 6, paddingHorizontal: 6, paddingVertical: 2, overflow: "hidden" },
    capEmpty: { fontSize: 13, color: t.textMuted, padding: 18 },
    capEditNameRow: { flexDirection: "row", alignItems: "center", gap: 8, marginTop: 4 },
    capCodeInput: { minHeight: 220, fontFamily: Platform.OS === "ios" ? "Menlo" : "monospace", fontSize: 12, textAlignVertical: "top", marginTop: 10 },
    capErr: { color: t.danger, fontSize: 12, marginTop: 8, marginHorizontal: 14 },
    capModalBackdrop: { flex: 1, backgroundColor: "rgba(0,0,0,0.4)", justifyContent: "flex-end" },
    capModalCard: { maxHeight: "88%", borderTopLeftRadius: 16, borderTopRightRadius: 16, padding: 16 },
    capModalTitle: { fontSize: 17, fontWeight: "700", marginBottom: 10 },
    capModalActions: { flexDirection: "row", alignItems: "center", gap: 20, paddingTop: 12 },
    capModalBtn: { fontSize: 15 },
    sheetPills: { paddingHorizontal: 18, paddingVertical: 10, gap: 8 },
    // Bordered + bg one step darker than the sheet so each pill reads as a
    // distinct, tappable element (previously chipBg on surface was near-invisible
    // in dark mode).
    sheetPill: {
      flexDirection: "row",
      alignItems: "center",
      gap: 5,
      paddingHorizontal: 15,
      paddingVertical: 9,
      borderRadius: 18,
      backgroundColor: t.bg,
      borderWidth: 1,
      borderColor: t.border,
    },
    sheetPillActive: { backgroundColor: t.accent, borderColor: t.accent },
    sheetPillText: { fontSize: 14, color: t.textMuted, fontWeight: "600" },
    sheetPillTextActive: { color: "#fff", fontWeight: "700" },
    sheetDone: {
      marginHorizontal: 18,
      marginTop: 18,
      paddingVertical: 13,
      borderRadius: 10,
      backgroundColor: t.accent,
      alignItems: "center",
    },
    sheetDoneText: { color: "#fff", fontSize: 15, fontWeight: "700" },
    // Secondary sheet action (Cancel): a muted, themed surface with a border —
    // reads as a soft pastel chip on both light and dark instead of a bright box.
    sheetCancel: {
      marginHorizontal: 18,
      marginTop: 10,
      paddingVertical: 13,
      borderRadius: 10,
      backgroundColor: t.chipBg,
      borderWidth: 1,
      borderColor: t.border,
      alignItems: "center",
    },
    sheetCancelText: { color: t.textMuted, fontSize: 15, fontWeight: "600" },
    // Session settings sheet (system prompt / goal / loops / filter / notify)
    ssScroll: { maxHeight: 460 },
    ssScrollContent: { paddingBottom: 24 },
    ssInput: {
      marginHorizontal: 18,
      marginTop: 8,
      paddingHorizontal: 12,
      paddingVertical: 10,
      borderRadius: 10,
      borderWidth: 1,
      borderColor: t.border,
      backgroundColor: t.inputBg,
      color: t.text,
      fontSize: 14,
    },
    ssMultiline: { minHeight: 76, textAlignVertical: "top" },
    ssRow: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      marginHorizontal: 18,
      marginTop: 12,
      paddingVertical: 6,
    },
    ssRowLabel: { fontSize: 15, color: t.text, fontWeight: "600" },
    ssRowHint: { fontSize: 12, color: t.textMuted, marginTop: 2, maxWidth: 230 },
    // Filter chips (You / Assistant / Tools / System) — grid of toggles
    ssFilterGrid: { flexDirection: "row", flexWrap: "wrap", gap: 8, paddingHorizontal: 18, marginTop: 8 },
    ssFilterChip: {
      flexDirection: "row",
      alignItems: "center",
      gap: 5,
      paddingHorizontal: 13,
      paddingVertical: 8,
      borderRadius: 16,
      borderWidth: 1,
      borderColor: t.border,
      backgroundColor: t.bg,
    },
    ssFilterChipOn: { backgroundColor: t.accent, borderColor: t.accent },
    ssFilterText: { fontSize: 13, color: t.textMuted, fontWeight: "600" },
    ssFilterTextOn: { color: "#fff" },
    // Loop list rows
    ssLoopRow: {
      flexDirection: "row",
      alignItems: "center",
      gap: 8,
      marginHorizontal: 18,
      marginTop: 8,
      paddingHorizontal: 12,
      paddingVertical: 10,
      borderRadius: 10,
      borderWidth: 1,
      borderColor: t.border,
      backgroundColor: t.bg,
    },
    ssLoopPrompt: { flex: 1, fontSize: 13, color: t.text },
    ssLoopInterval: { fontSize: 12, color: t.textMuted, fontWeight: "700" },
    ssLoopAddRow: { flexDirection: "row", alignItems: "center", gap: 8, marginHorizontal: 18, marginTop: 8 },
    ssLoopIntervalInput: {
      width: 56,
      paddingHorizontal: 10,
      paddingVertical: 10,
      borderRadius: 10,
      borderWidth: 1,
      borderColor: t.border,
      backgroundColor: t.inputBg,
      color: t.text,
      textAlign: "center",
      fontSize: 14,
    },
    ssAddBtn: {
      paddingHorizontal: 16,
      paddingVertical: 10,
      borderRadius: 10,
      backgroundColor: t.accent,
      alignItems: "center",
    },
    ssAddBtnText: { color: "#fff", fontSize: 14, fontWeight: "700" },
    ssSaved: { fontSize: 11, color: t.accent, fontWeight: "700" },
    // --- Session profile screen ---
    spHeader: { alignItems: "center", paddingTop: 20, paddingBottom: 8, paddingHorizontal: 24 },
    spTitleInput: {
      marginTop: 14,
      fontSize: 18,
      fontWeight: "700",
      textAlign: "center",
      minWidth: 160,
      maxWidth: "90%",
      paddingVertical: 6,
      paddingHorizontal: 12,
      borderWidth: StyleSheet.hairlineWidth,
      borderRadius: 10,
    },
    spAvatarGrid: {
      flexDirection: "row",
      flexWrap: "wrap",
      gap: 10,
      paddingHorizontal: 16,
      paddingTop: 4,
    },
    spAvatarCell: {
      width: 48,
      height: 48,
      borderRadius: 12,
      borderWidth: 1.5,
      alignItems: "center",
      justifyContent: "center",
    },
    // Markdown rendering (Markdown.tsx also themes code/tables inline off useTheme)
    mdText: { fontSize: 15, lineHeight: 21, color: t.text },
    mdPara: { marginBottom: 2 },
    mdBold: { fontWeight: "700" },
    mdItalic: { fontStyle: "italic" },
    mdH1: { fontSize: 18, fontWeight: "700", marginTop: 8, marginBottom: 2 },
    mdH3: { fontSize: 16, fontWeight: "700", marginTop: 6, marginBottom: 2 },
    mdLink: { color: t.accent, textDecorationLine: "underline" },
    mdCodeInline: {
      fontFamily: mono,
      fontSize: 13.5,
      backgroundColor: t.codeBg,
      color: t.codeText,
    },
    mdCodeBlock: {
      backgroundColor: t.codeBg,
      borderRadius: 8,
      paddingHorizontal: 10,
      paddingVertical: 8,
      marginVertical: 6,
    },
    mdCodeText: {
      fontFamily: mono,
      fontSize: 12.5,
      lineHeight: 18,
      color: t.codeText,
    },
    mdLi: { flexDirection: "row", alignItems: "flex-start", gap: 6, marginVertical: 1 },
    mdBullet: { width: 18 },
    mdTableWrap: { marginVertical: 6 },
    mdScroll: { flexGrow: 0 },
    // Reply bar (what you're replying to) + swipe affordance
    replyBar: {
      flexDirection: "row",
      alignItems: "center",
      gap: 8,
      marginHorizontal: 10,
      marginBottom: 6,
      paddingVertical: 8,
      paddingRight: 10,
      borderRadius: 10,
      overflow: "hidden",
      backgroundColor: t.chipBg,
    },
    replyBarAccent: { width: 3, alignSelf: "stretch", backgroundColor: t.accent },
    replyBarText: { flex: 1, fontSize: 12.5, color: t.textMuted },
    replyBarX: { fontSize: 13, fontWeight: "700", color: t.textMuted },
    swipeHint: {
      position: "absolute",
      left: 16,
      top: 0,
      bottom: 0,
      justifyContent: "center",
    },
    swipeHintText: { fontSize: 18, color: t.textMuted },
    mdRow: { flexDirection: "row" },
    mdHeadRow: { borderBottomWidth: 1, borderBottomColor: t.border },
    mdCell: {
      minWidth: 96,
      maxWidth: 240,
      paddingVertical: 5,
      paddingHorizontal: 8,
      fontSize: 13,
      color: t.text,
      borderRightWidth: StyleSheet.hairlineWidth,
      borderRightColor: t.border,
    },
    mdHeadCell: { fontWeight: "700", color: t.text },
    mdQuote: {
      borderLeftWidth: 3,
      borderLeftColor: t.border,
      paddingLeft: 10,
      marginVertical: 4,
    },
    mdQuoteText: { color: t.textMuted, fontStyle: "italic" },
    mdHr: { height: StyleSheet.hairlineWidth, backgroundColor: t.border, marginVertical: 10 },
    // Slash-command autocomplete
    slashList: {
      marginHorizontal: 8,
      marginBottom: 6,
      borderRadius: 12,
      backgroundColor: t.surface,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: t.border,
      overflow: "hidden",
    },
    slashRow: { paddingHorizontal: 14, paddingVertical: 10, borderBottomWidth: StyleSheet.hairlineWidth, borderBottomColor: t.border },
    slashName: { fontSize: 14.5, fontWeight: "700", color: t.text },
    slashDesc: { fontSize: 12, color: t.textMuted, marginTop: 2 },
    // Queued messages
    queueWrap: { flexDirection: "row", flexWrap: "wrap", gap: 6, paddingHorizontal: 12, paddingBottom: 4 },
    queueChip: {
      flexDirection: "row",
      alignItems: "center",
      gap: 6,
      maxWidth: 240,
      paddingHorizontal: 10,
      paddingVertical: 5,
      borderRadius: 12,
      backgroundColor: t.chipBg,
      borderWidth: 1,
      borderColor: t.border,
    },
    queueChipText: { flexShrink: 1, fontSize: 12, color: t.text },
    queueChipX: { fontSize: 12, color: t.textMuted, fontWeight: "700" },
    // Chat search
    searchWrap: { paddingHorizontal: 12, paddingVertical: 8, backgroundColor: t.surface },
    searchInput: {
      height: 38,
      borderRadius: 19,
      paddingHorizontal: 14,
      fontSize: 15,
      backgroundColor: t.inputBg,
      color: t.text,
    },
    // Action sheet (long-press a chat)
    actionSheetTitle: { fontSize: 15, fontWeight: "700", color: t.text, paddingHorizontal: 20, paddingBottom: 4 },
    actionRow: { paddingHorizontal: 20, paddingVertical: 15, borderTopWidth: StyleSheet.hairlineWidth, borderTopColor: t.border },
    actionText: { fontSize: 16, color: t.text },
    actionDanger: { color: t.danger, fontWeight: "600" },
    // File browser
    fsPath: { fontSize: 12, color: t.textMuted, paddingHorizontal: 14, paddingVertical: 8, backgroundColor: t.surface },
    fsBusy: { paddingVertical: 6, alignItems: "center", backgroundColor: t.surface },
    fsRow: {
      flexDirection: "row",
      alignItems: "center",
      gap: 10,
      paddingHorizontal: 16,
      paddingVertical: 12,
      borderBottomWidth: StyleSheet.hairlineWidth,
      borderBottomColor: t.border,
    },
    fsIcon: { fontSize: 16, width: 22 },
    fsName: { flex: 1, fontSize: 15, color: t.text, fontWeight: "500" },
    fsFile: { fontWeight: "400", color: t.textMuted },
    fsSize: { fontSize: 12, color: t.textMuted },
    // Session info / stats
    statGrid: { flexDirection: "row", flexWrap: "wrap", gap: 10 },
    statCard: { flexGrow: 1, minWidth: 100, borderRadius: 12, paddingVertical: 14, paddingHorizontal: 12, backgroundColor: t.surface },
    statValue: { fontSize: 22, fontWeight: "700", color: t.text },
    statLabel: { fontSize: 12, marginTop: 2, color: t.textMuted },
    statPath: { fontSize: 13, paddingHorizontal: 16, fontFamily: mono, color: t.textMuted },
    toolBarRow: { flexDirection: "row", alignItems: "center", gap: 8, marginVertical: 4 },
    toolBarName: { width: 110, fontSize: 13, color: t.text },
    toolBarTrack: { flex: 1, height: 8, borderRadius: 4, overflow: "hidden", backgroundColor: t.chipBg },
    toolBarFill: { height: 8, borderRadius: 4, backgroundColor: t.accent },
    toolBarCount: { width: 40, fontSize: 12, textAlign: "right", color: t.textMuted },
    // Composer: mode pills + steer/queue actions
    modeBar: {
      flexDirection: "row",
      alignItems: "center",
      gap: 6,
      paddingHorizontal: 8,
      paddingTop: 6,
      paddingBottom: 2,
      backgroundColor: t.surface,
    },
    modePill: { paddingHorizontal: 10, paddingVertical: 5, borderRadius: 14, backgroundColor: t.chipBg },
    modePillActive: { backgroundColor: t.accent },
    modePillText: { fontSize: 12, color: t.textMuted },
    modePillTextActive: { color: "#fff" },
    actionBtn: {
      marginLeft: 8,
      borderRadius: 22,
      height: 44,
      paddingHorizontal: 14,
      alignItems: "center",
      justifyContent: "center",
      backgroundColor: t.accent,
    },
    actionBtnAlt: { backgroundColor: t.textMuted },
    actionBtnText: { color: "#fff", fontSize: 14, fontWeight: "700" },
    // Permission (Allow/Deny) card — amber, kept literal
    permCard: {
      backgroundColor: "#efe9dd",
      borderColor: "#d6c39a",
      borderWidth: 1,
      borderRadius: 10,
      marginHorizontal: 10,
      marginVertical: 6,
      padding: 12,
    },
    permTitle: { fontSize: 14, fontWeight: "700", color: "#7a6a45" },
    permInput: { fontSize: 11, color: "#8a7a58", marginTop: 4 },
    permBtnRow: { flexDirection: "row", justifyContent: "flex-end", marginTop: 10 },
    permDeny: { paddingVertical: 8, paddingHorizontal: 16, borderRadius: 8, backgroundColor: "#eee", marginLeft: 10 },
    permAllow: { paddingVertical: 8, paddingHorizontal: 16, borderRadius: 8, backgroundColor: t.accent, marginLeft: 10 },
    permDenyText: { color: "#333", fontWeight: "600" },
    permAllowText: { color: "#fff", fontWeight: "700" },
    // Collapsible agent "steps" under the final response
    stepsToggle: {
      flexDirection: "row",
      alignItems: "center",
      alignSelf: "flex-start",
      marginTop: 8,
      paddingVertical: 4,
    },
    stepsToggleText: { fontSize: 12, color: t.accent, fontWeight: "600" },
    stepsBox: { marginTop: 6, borderTopWidth: StyleSheet.hairlineWidth, borderTopColor: t.border, paddingTop: 6 },
    // Proposed-plan card (ExitPlanMode). Accent-outlined so it reads as a distinct
    // artifact, not just another paragraph of the reply.
    planCard: { borderWidth: 1, borderRadius: 12, marginVertical: 6, overflow: "hidden" },
    planHeader: { flexDirection: "row", alignItems: "center", gap: 7, paddingHorizontal: 12, paddingVertical: 9 },
    planTitle: { flex: 1, fontSize: 14, fontWeight: "700" },
    planBody: { paddingHorizontal: 12, paddingBottom: 10, paddingTop: 2 },
    toolResult: {
      marginTop: 4,
      padding: 8,
      borderRadius: 6,
      backgroundColor: t.codeBg,
    },
    toolResultErr: { backgroundColor: t.dangerBg },
    toolResultText: { fontFamily: "Courier", fontSize: 11, color: t.codeText },
    finalText: { fontSize: 15, color: t.text, lineHeight: 21 },
    // Dropdown (permission mode / model)
    ddTrigger: {
      paddingHorizontal: 10,
      paddingVertical: 6,
      borderRadius: 8,
      backgroundColor: t.chipBg,
    },
    ddTriggerText: { fontSize: 13, color: t.text, fontWeight: "600" },
    ddScrim: { flex: 1, backgroundColor: "rgba(0,0,0,0.35)", justifyContent: "flex-end" },
    ddSheet: { backgroundColor: t.surface, borderTopLeftRadius: 16, borderTopRightRadius: 16, paddingVertical: 8, paddingBottom: 28 },
    ddItem: { paddingHorizontal: 20, paddingVertical: 14 },
    ddItemText: { fontSize: 16, color: t.textMuted },
    ddItemActive: { fontWeight: "700", color: t.text },
    // WhatsApp-style header
    headerTitleWrap: { alignItems: "center" },
    headerTitleText: { fontSize: 17, fontWeight: "600", color: t.text },
    headerSubtitle: { fontSize: 12, color: t.accent, fontWeight: "600" },
    // Live "working on it" bubble
    workingBubble: {
      alignSelf: "flex-start",
      backgroundColor: t.bubbleAgent,
      borderRadius: 12,
      paddingVertical: 10,
      paddingHorizontal: 12,
      marginVertical: 3,
      marginHorizontal: 10,
      maxWidth: "82%",
      flexDirection: "row",
      alignItems: "center",
      gap: 8,
    },
    workingText: { fontSize: 14, color: t.textMuted, fontStyle: "italic", flexShrink: 1 },
  })
  return s
}

export type AppStyles = ReturnType<typeof buildStyles>

// Memo cache: LIGHT/DARK are stable singletons, so buildStyles runs at most twice.
const _cache = new Map<Theme, AppStyles>()

export function makeStyles(t: Theme): AppStyles {
  let s = _cache.get(t)
  if (!s) {
    s = buildStyles(t)
    _cache.set(t, s)
  }
  return s
}

/** Hook: the stylesheet for the active theme. Repaints on theme change. */
export function useStyles(): AppStyles {
  return makeStyles(useTheme())
}
